# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/GitProjects/rhc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/GitProjects/rhc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/GitProjects/rhc/CMakeFiles /storage/emulated/0/GitProjects/rhc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/GitProjects/rhc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named socket_client

# Build rule for target.
socket_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 socket_client
.PHONY : socket_client

# fast build rule for target.
socket_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket_client.dir/build.make CMakeFiles/socket_client.dir/build
.PHONY : socket_client/fast

#=============================================================================
# Target rules for targets named socket_server

# Build rule for target.
socket_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 socket_server
.PHONY : socket_server

# fast build rule for target.
socket_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket_server.dir/build.make CMakeFiles/socket_server.dir/build
.PHONY : socket_server/fast

#=============================================================================
# Target rules for targets named safety

# Build rule for target.
safety: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 safety
.PHONY : safety

# fast build rule for target.
safety/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/safety.dir/build.make CMakeFiles/safety.dir/build
.PHONY : safety/fast

#=============================================================================
# Target rules for targets named hashmap

# Build rule for target.
hashmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hashmap
.PHONY : hashmap

# fast build rule for target.
hashmap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashmap.dir/build.make CMakeFiles/hashmap.dir/build
.PHONY : hashmap/fast

#=============================================================================
# Target rules for targets named dynarray

# Build rule for target.
dynarray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dynarray
.PHONY : dynarray

# fast build rule for target.
dynarray/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynarray.dir/build.make CMakeFiles/dynarray.dir/build
.PHONY : dynarray/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

examples/dynarray.o: examples/dynarray.c.o
.PHONY : examples/dynarray.o

# target to build an object file
examples/dynarray.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynarray.dir/build.make CMakeFiles/dynarray.dir/examples/dynarray.c.o
.PHONY : examples/dynarray.c.o

examples/dynarray.i: examples/dynarray.c.i
.PHONY : examples/dynarray.i

# target to preprocess a source file
examples/dynarray.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynarray.dir/build.make CMakeFiles/dynarray.dir/examples/dynarray.c.i
.PHONY : examples/dynarray.c.i

examples/dynarray.s: examples/dynarray.c.s
.PHONY : examples/dynarray.s

# target to generate assembly for a file
examples/dynarray.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynarray.dir/build.make CMakeFiles/dynarray.dir/examples/dynarray.c.s
.PHONY : examples/dynarray.c.s

examples/hashmap.o: examples/hashmap.c.o
.PHONY : examples/hashmap.o

# target to build an object file
examples/hashmap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashmap.dir/build.make CMakeFiles/hashmap.dir/examples/hashmap.c.o
.PHONY : examples/hashmap.c.o

examples/hashmap.i: examples/hashmap.c.i
.PHONY : examples/hashmap.i

# target to preprocess a source file
examples/hashmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashmap.dir/build.make CMakeFiles/hashmap.dir/examples/hashmap.c.i
.PHONY : examples/hashmap.c.i

examples/hashmap.s: examples/hashmap.c.s
.PHONY : examples/hashmap.s

# target to generate assembly for a file
examples/hashmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashmap.dir/build.make CMakeFiles/hashmap.dir/examples/hashmap.c.s
.PHONY : examples/hashmap.c.s

examples/main.o: examples/main.c.o
.PHONY : examples/main.o

# target to build an object file
examples/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/examples/main.c.o
.PHONY : examples/main.c.o

examples/main.i: examples/main.c.i
.PHONY : examples/main.i

# target to preprocess a source file
examples/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/examples/main.c.i
.PHONY : examples/main.c.i

examples/main.s: examples/main.c.s
.PHONY : examples/main.s

# target to generate assembly for a file
examples/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/examples/main.c.s
.PHONY : examples/main.c.s

examples/safety.o: examples/safety.c.o
.PHONY : examples/safety.o

# target to build an object file
examples/safety.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/safety.dir/build.make CMakeFiles/safety.dir/examples/safety.c.o
.PHONY : examples/safety.c.o

examples/safety.i: examples/safety.c.i
.PHONY : examples/safety.i

# target to preprocess a source file
examples/safety.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/safety.dir/build.make CMakeFiles/safety.dir/examples/safety.c.i
.PHONY : examples/safety.c.i

examples/safety.s: examples/safety.c.s
.PHONY : examples/safety.s

# target to generate assembly for a file
examples/safety.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/safety.dir/build.make CMakeFiles/safety.dir/examples/safety.c.s
.PHONY : examples/safety.c.s

examples/socket_client.o: examples/socket_client.c.o
.PHONY : examples/socket_client.o

# target to build an object file
examples/socket_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket_client.dir/build.make CMakeFiles/socket_client.dir/examples/socket_client.c.o
.PHONY : examples/socket_client.c.o

examples/socket_client.i: examples/socket_client.c.i
.PHONY : examples/socket_client.i

# target to preprocess a source file
examples/socket_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket_client.dir/build.make CMakeFiles/socket_client.dir/examples/socket_client.c.i
.PHONY : examples/socket_client.c.i

examples/socket_client.s: examples/socket_client.c.s
.PHONY : examples/socket_client.s

# target to generate assembly for a file
examples/socket_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket_client.dir/build.make CMakeFiles/socket_client.dir/examples/socket_client.c.s
.PHONY : examples/socket_client.c.s

examples/socket_server.o: examples/socket_server.c.o
.PHONY : examples/socket_server.o

# target to build an object file
examples/socket_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket_server.dir/build.make CMakeFiles/socket_server.dir/examples/socket_server.c.o
.PHONY : examples/socket_server.c.o

examples/socket_server.i: examples/socket_server.c.i
.PHONY : examples/socket_server.i

# target to preprocess a source file
examples/socket_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket_server.dir/build.make CMakeFiles/socket_server.dir/examples/socket_server.c.i
.PHONY : examples/socket_server.c.i

examples/socket_server.s: examples/socket_server.c.s
.PHONY : examples/socket_server.s

# target to generate assembly for a file
examples/socket_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket_server.dir/build.make CMakeFiles/socket_server.dir/examples/socket_server.c.s
.PHONY : examples/socket_server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dynarray"
	@echo "... hashmap"
	@echo "... main"
	@echo "... safety"
	@echo "... socket_client"
	@echo "... socket_server"
	@echo "... examples/dynarray.o"
	@echo "... examples/dynarray.i"
	@echo "... examples/dynarray.s"
	@echo "... examples/hashmap.o"
	@echo "... examples/hashmap.i"
	@echo "... examples/hashmap.s"
	@echo "... examples/main.o"
	@echo "... examples/main.i"
	@echo "... examples/main.s"
	@echo "... examples/safety.o"
	@echo "... examples/safety.i"
	@echo "... examples/safety.s"
	@echo "... examples/socket_client.o"
	@echo "... examples/socket_client.i"
	@echo "... examples/socket_client.s"
	@echo "... examples/socket_server.o"
	@echo "... examples/socket_server.i"
	@echo "... examples/socket_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

